config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_scope :user do
    root to: "devise/sessions#new"
  end
  
  resources :social_accounts, only: :index do
    collection do
      put 'search_accounts'
      get 'avaliable_business_accounts'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/business_account.rb
class BusinessAccount < ApplicationRecord
  validates :account_id, :username, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.api_access_token = auth.info.access_token
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  protected
    def after_sign_in_path_for(resource)
      social_accounts_path
    end
end

app/controllers/social_accounts_controller.rb
class SocialAccountsController < ApplicationController

  def index
  end

  def search_accounts
    url = set_base_api_url
    page_name = params[:page_name] rescue ''
    search = "#{set_base_api_url}search?access_token=EAATZBhW2WqcMBAARQ69vfTdWLcDnoWDWrU1s6r6U4XtoNADqmPobJ2WEKk5wLSlc58LP6yjZBz7eWnJnUKFAxxoVs73TLLkJQF3rVCsJHDrdldLUtxNlEPxWbB2Atgjzoft1gPcn4WG0hIQgFOAjc9HyZA3QMTKwB0J9nJa8lWhymTIUxyZBkzeyxTOkeou8Hm7pIGnkngZDZD&q=#{page_name}&type=page"
    response = HTTParty.get(search)
    if response.present? && response.parsed_response['data'].present?
      response = response.parsed_response['data']
      facebook_page_ids = response.map{|f| f['id']}
      facebook_page_ids.each do |facebook_page_id|
        address_url = "#{set_base_api_url}/#{facebook_page_id}?access_token=EAATZBhW2WqcMBAARQ69vfTdWLcDnoWDWrU1s6r6U4XtoNADqmPobJ2WEKk5wLSlc58LP6yjZBz7eWnJnUKFAxxoVs73TLLkJQF3rVCsJHDrdldLUtxNlEPxWbB2Atgjzoft1gPcn4WG0hIQgFOAjc9HyZA3QMTKwB0J9nJa8lWhymTIUxyZBkzeyxTOkeou8Hm7pIGnkngZDZD&fields=location"
        address = HTTParty.get(address_url)
        if address.parsed_response.present? && address.parsed_response["location"].present?
          latitude = address.parsed_response["location"]["latitude"] rescue ''
          longitude = address.parsed_response["location"]["longitude"] rescue ''
          search_url = "#{set_base_api_url}search?access_token=EAATZBhW2WqcMBAARQ69vfTdWLcDnoWDWrU1s6r6U4XtoNADqmPobJ2WEKk5wLSlc58LP6yjZBz7eWnJnUKFAxxoVs73TLLkJQF3rVCsJHDrdldLUtxNlEPxWbB2Atgjzoft1gPcn4WG0hIQgFOAjc9HyZA3QMTKwB0J9nJa8lWhymTIUxyZBkzeyxTOkeou8Hm7pIGnkngZDZD&q=''&type=page&type=place&center=#{latitude},#{longitude}&distance=16093"
          response_on_location = HTTParty.get(search_url)
          if response_on_location.present? && response_on_location.parsed_response['data'].present?
            facebook_pages_on_location = response_on_location.parsed_response['data']
            facebook_page_ids = response.map{|f| f['id']}
            facebook_page_ids.each do |facebook_page_id|
              insta_account_url = "#{set_base_api_url}/#{facebook_page_id}?access_token=EAATZBhW2WqcMBAARQ69vfTdWLcDnoWDWrU1s6r6U4XtoNADqmPobJ2WEKk5wLSlc58LP6yjZBz7eWnJnUKFAxxoVs73TLLkJQF3rVCsJHDrdldLUtxNlEPxWbB2Atgjzoft1gPcn4WG0hIQgFOAjc9HyZA3QMTKwB0J9nJa8lWhymTIUxyZBkzeyxTOkeou8Hm7pIGnkngZDZD&fields=instagram_business_account"
              business_response = HTTParty.get(insta_account_url)
              business_response = business_response.parsed_response["instagram_business_account"] rescue ''
              if business_response.present?
                insta_account_id = business_response["id"] 
                insta_business_account_detail_url = "#{set_base_api_url}/#{insta_account_id}?access_token=EAATZBhW2WqcMBAARQ69vfTdWLcDnoWDWrU1s6r6U4XtoNADqmPobJ2WEKk5wLSlc58LP6yjZBz7eWnJnUKFAxxoVs73TLLkJQF3rVCsJHDrdldLUtxNlEPxWbB2Atgjzoft1gPcn4WG0hIQgFOAjc9HyZA3QMTKwB0J9nJa8lWhymTIUxyZBkzeyxTOkeou8Hm7pIGnkngZDZD&fields=biography,id,username,website,ig_id,followers_count,media_count,name,profile_picture_url" if insta_account_id.present?
                insta_response = HTTParty.get(insta_business_account_detail_url)
                account_detail = insta_response.parsed_response rescue ''
                business_account = BusinessAccount.create(account_id: account_detail['id'], 
                                                          name: account_detail['name'],
                                                          profile_picture_url: account_detail['profile_picture_url'],
                                                          followers_count: account_detail['followers_count'],
                                                          media_count: account_detail['media_count'],
                                                          username: account_detail['media_count'],
                                                          ig_id: account_detail['ig_id'] )
              end
            end
          end
        end
      end
    end
    redirect_to avaliable_business_accounts_social_accounts_path
  end

  def avaliable_business_accounts
    @business_accounts = BusinessAccount.all
  end

  def set_base_api_url
    'https://graph.facebook.com/v2.10/'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/social_accounts_helper.rb
module SocialAccountsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstaGeoFinder</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="user_nav">
      <% if user_signed_in? %>
        Signed in as <%= current_user.email %>. Not you?
        <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/social_accounts/avaliable_business_accounts.html.erb
<div>
  <table>
    <thead>
      <tr>
        <th>Id#</th>
        <th>Profile Pic</th>
        <th>Account Id</th>
        <th>Account Name</th>
        <th>User Name</th>
        <th>Followers count</th>
        <th>Media count</th>
        <th>ig id</th>
      </tr>
    </thead>
    <tbody>
      <% unless @business_accounts.blank? %>
        <% @business_accounts.each do |account| %>
          <tr>
            <td>
              <%= link_to account.id, '' %>
            </td>
            <td>
              <%= image_tag(account.profile_picture_url, size: "50x50") rescue ''%>
            </td>
            <td>
              <%= account.account_id %>
            </td>
            <td>
              <%= account.name %>
            </td>
            <td>
              <%= account.username %>
            </td>
            <td>
              <%= account.followers_count %>
            </td>
            <td>
              <%= account.media_count %>
            </td>
            <td>
              <%= account.ig_id %>
            </td>
          </tr>
        <% end %>
      <% else %>
        <tr>
          <td class="bg-info text-center" colspan="10">No Business on this location To Display.</td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/social_accounts/index.html.erb
Welcome to social accounts index

<%= form_tag search_accounts_social_accounts_path, :method => :put do %>
  <%= label_tag 'Please enter your page name'%><br>
  <%= text_field_tag "page_name", ''%>
  <%=submit_tag 'Search Accounts'%>
<% end %>